### ISSUE TITLE
docker-compose pull does not do anything on WSL

### ISSUE THREAD

**Issue by kchiu002** [ODU-CGA-CubeSat/sealion-workspace-image#8]
The command `docker-compose pull` is unable to perform its function.
It simply just ends the command immediately after input.

docker-composer version:
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

docker vesion:
```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

docker-compose config:
```
services:
  kasm:
    build:
      context: /home/kchiu002/kasm-sealion-workspace
    environment:
      VNC_PW: password
    image: ghcr.io/capsulecorplab/kasm-sealion-workspace:main
    network_mode: bridge
    ports:
    - published: 6901
      target: 6901
    security_opt:
    - seccomp=unconfined
    shm_size: 512m
    stdin_open: true
    tty: true
    volumes:
    - source: /home/kchiu002/kasm-sealion-workspace/kasm_user
      target: /home/kasm-user
      type: bind
version: '3.7'
```
